import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppColors } from '@/constants/app-theme';
import { useProgress } from '@/hooks/use-progress';
import type { LanguageCode } from '@/types/learning';
const STEPS=['Bienvenido a LinguaFox 🦊','Practica con lecciones, audio y quizzes','Habla con Fox y personajes originales','Elige tu idioma'];
export function OnboardingScreen(){const {completeOnboarding,setLanguage}=useProgress();const [step,setStep]=useState(0);const [language,setLocalLanguage]=useState<LanguageCode>('en');const finish=():void=>{setLanguage(language);completeOnboarding();router.replace('/');};return <SafeAreaView style={s.safe}><View style={s.page}><Text style={s.logo}>🦊</Text><Text style={s.title}>{STEPS[step]}</Text>{step===3?<View style={s.options}>{(['en','fr'] as const).map(code=><Pressable key={code} style={[s.option,language===code&&s.selected]} onPress={()=>setLocalLanguage(code)}><Text style={s.text}>{code==='en'?'🇬🇧 Inglés':'🇫🇷 Francés'}</Text></Pressable>)}</View>:<Text style={s.copy}>{step===0?'Aprende a tu ritmo, gana estrellas y mantén tu racha.':step===1?'Escucha la pronunciación y repasa con feedback inmediato.':'Conversaciones guiadas y divertidas, sin presión.'}</Text>}<Pressable style={s.button} onPress={step===3?finish:()=>setStep(value=>value+1)}><Text style={s.buttonText}>{step===3?'Empezar':'Siguiente'}</Text></Pressable></View></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:AppColors.background},page:{flex:1,padding:28,alignItems:'center',justifyContent:'center',gap:20,maxWidth:600,width:'100%',alignSelf:'center'},logo:{fontSize:72},title:{color:AppColors.text,fontSize:28,fontWeight:'900',textAlign:'center'},copy:{color:AppColors.textMuted,fontSize:17,textAlign:'center',lineHeight:25},options:{width:'100%',gap:10},option:{backgroundColor:AppColors.surface,borderRadius:14,padding:16,alignItems:'center'},selected:{borderColor:AppColors.primary,borderWidth:2},text:{color:AppColors.text,fontWeight:'800',fontSize:17},button:{backgroundColor:AppColors.primary,borderRadius:14,padding:16,width:'100%',alignItems:'center',marginTop:12},buttonText:{color:AppColors.text,fontWeight:'900',fontSize:16}});
